#!/bin/bash

apt upgrade

sleep 1s

apt update

sleep 2s

figlet -c Setup

sleep 2s

apt install python

sleep 3s

apt install toilet

sleep 3s

echo bluilding required dependencies

sleep 4s


toilet -F metal Enthernet®

sleep 5s

echo to run programme type ./srch.sh and hit enter

chmod +x srch.sh

./srch.sh
